version: '3.7'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./.docker/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'database'
      MYSQL_PASSWORD: 'database'
      MYSQL_ROOT_PASSWORD: 'database'

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
        - .:/var/www/html
        - ./.docker/php.ini:/usr/local/etc/php/conf.d/php.ini

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: database
      PMA_PASSWORD: database
